### ISSUE TITLE
Support of SSO with profile

### ISSUE THREAD

**Issue by mberchon** [bbstilson/sbt-codeartifact#12]
Hello,

In our organization, we are intensively using `aws configure sso`
In order to get and set our AWS access (in opposition to exporting env variable) in the context of our workstation

It would be nice to have support of it. It just requires some additional dependency

Will create a pull request accordingly.

**Comment by mberchon** [comment]
Unfortunately, I am not authorized to create pull request.

Here are the changes I did to make it work with 'aws configure sso'

core/build.sbt:
```
enablePlugins(SbtPlugin)

name := "sbt-codeartifact-core"

libraryDependencies ++= Seq(
  "software.amazon.awssdk" % "sso" % "2.17.103",
  "software.amazon.awssdk" % "codeartifact" % "2.17.103",
  "software.amazon.awssdk" % "sts" % "2.17.103",
  "com.lihaoyi" %% "requests" % "0.6.9",
  "com.lihaoyi" %% "os-lib" % "0.7.8",
  "com.lihaoyi" %% "utest" % "0.7.10" % Test
)

testFrameworks += new TestFramework("utest.runner.Framework")
```

**Comment by bbstilson** [comment]
@mberchon this seems reasonable. You should be able to fork this repo and create a PR to that one and it will land here. If not, I can add this after work today.

**Comment by mberchon** [comment]
@bbstilson: Thx for your quick reply. PR has been sent. Have a nice day.

**Comment by mberchon** [comment]
Hello @bbstilson
I have recreated the PR with add-aws-sso branch

**Comment by bbstilson** [comment]
Fixed in https://github.com/bbstilson/sbt-codeartifact/pull/16
