### ISSUE TITLE
Fix binary Scala version detection for Scala 3

### ISSUE THREAD

**Issue by reddicj** [bbstilson/sbt-codeartifact#19]
Hi thanks for this useful plugin. I note that the issue with Scala 3 has been fixed but there is no release yet with this change. Any chance this can be released soon? Many thanks.

**Comment by bbstilson** [comment]
Sorry! Done! 0.2.4 is on its way.

**Comment by regiskuckaertz** [comment]
Thank you 🙌

**Comment by reddicj** [comment]
Hi, has 0.2.4 been released yet? Thanks.

**Comment by bbstilson** [comment]
Opened an issue here: https://github.com/sbt/sbt-ci-release/issues/237. I suspect it's not an issue on their end but afaict nothing has changed about how this library is deployed.

**Comment by bbstilson** [comment]
Opened an issue with [Sonatype](https://issues.sonatype.org/browse/MVNCENTRAL-7357). Will report back when I hear from them.

**Comment by reddicj** [comment]
Many thanks for taking the time to look into this, much appreciated.

**Comment by bbstilson** [comment]
Heard back from someone at Sonatype:

![image](https://user-images.githubusercontent.com/7949037/162798878-8f6ce7c8-7b2a-45af-ab15-e513da82ace3.png)

I'm keeping an eye on Maven and will update this ticket when the newest version is released (or not)

**Comment by bbstilson** [comment]
[0.2.4 has landed](https://search.maven.org/artifact/io.github.bbstilson/sbt-codeartifact/0.2.4/jar)! I really appreciate everyone's cooperation and patience. Let me know if there are any further issues.

**Comment by reddicj** [comment]
Thank you so much and for taking the time to follow this up. I and my colleagues really appreciate it.
