### ISSUE TITLE
sbt-codeartifact keeps on waiting for packages with publish / skip := true

### ISSUE THREAD

**Issue by neuromancer85** [bbstilson/sbt-codeartifact#2]
Hi, I have a few modules in my project that I don't need to publish on CodeArtifact.
For those modules I've set `publish / skip := true` and in fact they are not present in the repository.
However, sbt-codeartifact keeps on waiting for those packages to be present, resulting in a failed build.
A workaround that I found at the moment is to add
```
  .settings(
    publish / skip := true,
    codeArtifactWaitForPackageAvailable := false,
    codeArtifactUpdateStatus := false,
  )
```
to the skipped module.

**Comment by bbstilson** [comment]
[This test](https://github.com/bbstilson/sbt-codeartifact/pull/3/files#diff-58cff614a46c8a04a75c9a2ff7f0c22209a30d4cea7f0697c8a78cff394e093e) should cover this failure. I am publishing a patch version now (should be 0.1.4). Maven will take some time to update, but it's on its way.
