### ISSUE TITLE
When will v0.0.25 be released?

### ISSUE THREAD

**Issue by SimunKaracic** [bbstilson/sbt-codeartifact#28]
I'd really like to use the improvements made to used the credentials file when there's no env var.

I can see the version v0.0.25 in tags in the repo, but I can't download it, and latest I see in maven repos is v0.0.24.

**Comment by bbstilson** [comment]
Sorry about that. Work has been quite hectic (still working at a start up), and the release process was broken. 

I've updated all the release dependencies and have successfully released version 0.2.6

https://repo1.maven.org/maven2/io/github/bbstilson/sbt-codeartifact_2.12_1.0/0.2.6/

Let me know if you have any other issues.
