### ISSUE TITLE
One project with consumer and publisher

### ISSUE THREAD

**Issue by ramimoshe** [bbstilson/sbt-codeartifact#4]
how can i do that
`codeArtifactUrl` variable is "https://com-example-1234567890.d.codeartifact.us-west-2.amazonaws.com/maven/private" in case of producing
and kind of list in case of consuming 

can i change the name of `codeArtifactUrl` (e.g: codeArtifactUrlProducing & codeArtifactUrlConsuming)?

**Comment by bbstilson** [comment]
I recommend adding another resolver for consuming, like so:

```scala
resolvers += codeartifact.CodeArtifactRepo.fromUrl("consuming-url")
```

**Comment by bbstilson** [comment]
Hey I ended up adding another key `codeArtifactResolvers` for consuming. This will add credentials as well. Hopefully that helps. Checkout the readme [here](https://github.com/bbstilson/sbt-codeartifact#consuming) for an example.
